name: CI

'on':
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - run: npm ci
        name: Install

      - run: npm run lint
        name: ESLint

      - run: npm run prettier
        name: Prettier

      - run: npm run build
        name: Build
