name: CI

"on":
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        name: Use Node.js

      - run: npm ci
        name: Install

      - run: npm run build
        name: Build

      # - run: npm run lint
      # - name: Lint
